import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { ethers } from "ethers";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  console.log("🚀 Starting deployment...\n");

  const DEFAULT_PRIVATE_KEY =
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
  const rpcUrl =
    process.env.SEPOLIA_RPC_URL ||
    process.env.RPC_URL ||
    process.env.LOCALHOST_RPC_URL ||
    "http://127.0.0.1:8545";
  
  // Detect network from RPC URL
  let networkName = "localhost";
  if (rpcUrl.includes("sepolia")) {
    networkName = "sepolia";
  } else if (rpcUrl.includes("127.0.0.1") || rpcUrl.includes("localhost")) {
    networkName = "localhost";
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const deployer = new ethers.Wallet(
    process.env.PRIVATE_KEY || DEFAULT_PRIVATE_KEY,
    provider
  );

  console.log("📍 Deploying with account:", deployer.address);
  const balance = await provider.getBalance(deployer.address);
  console.log("💰 Account balance:", ethers.formatEther(balance), "ETH\n");

  const TREASURY_ADDRESS = process.env.TREASURY_ADDRESS || deployer.address;
  const CREATION_FEE = ethers.parseEther("0.01");

  console.log("⚙️  Configuration:");
  console.log("   Treasury Address:", TREASURY_ADDRESS);
  console.log("   Creation Fee:", ethers.formatEther(CREATION_FEE), "ETH\n");

  console.log("📝 Deploying VotingFactory...");
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/VotingFactory.sol/VotingFactory.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const VotingFactory = new ethers.ContractFactory(
    artifact.abi,
    artifact.bytecode,
    deployer
  );
  const factory = await VotingFactory.deploy(TREASURY_ADDRESS);
  await factory.waitForDeployment();

  const factoryAddress = await factory.getAddress();
  console.log("✅ VotingFactory deployed to:", factoryAddress);
  console.log("   Creation Fee:", ethers.formatEther(await factory.creationFee()), "ETH");
  console.log("   Treasury:", await factory.treasury());

  const chainId = (await provider.getNetwork()).chainId.toString();

  const deploymentInfo = {
    network: networkName,
    votingFactory: factoryAddress,
    treasury: TREASURY_ADDRESS,
    creationFee: ethers.formatEther(await factory.creationFee()),
    deployer: deployer.address,
    chainId,
    timestamp: new Date().toISOString(),
  };

  console.log("\n📋 Deployment Summary:");
  console.log(JSON.stringify(deploymentInfo, null, 2));

  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) fs.mkdirSync(deploymentsDir);

  const filename = `${networkName}-${Date.now()}.json`;
  fs.writeFileSync(
    path.join(deploymentsDir, filename),
    JSON.stringify(deploymentInfo, null, 2)
  );

  console.log("\n💾 Deployment info saved to:", filename);

  const envContent = `# Generated by deploy script - ${new Date().toISOString()}
NEXT_PUBLIC_VOTING_FACTORY_ADDRESS=${factoryAddress}
NEXT_PUBLIC_CHAIN_ID=${chainId}
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_walletconnect_project_id
`;

  const web3EnvPath = path.join(__dirname, "../.env.local.generated");
  fs.writeFileSync(web3EnvPath, envContent);

  const clientEnvPath = path.join(__dirname, "../../client/.env.local.generated");
  fs.writeFileSync(clientEnvPath, envContent);

  console.log("📝 Environment template saved to:", web3EnvPath);
  console.log("📝 Frontend environment template saved to:", clientEnvPath);
  console.log("\n🔗 Copy these values to client/.env.local:");
  console.log(`   NEXT_PUBLIC_VOTING_FACTORY_ADDRESS=${factoryAddress}`);
  console.log(`   NEXT_PUBLIC_CHAIN_ID=${chainId}`);

  if (networkName !== "localhost" && networkName !== "hardhat") {
    console.log("\n📝 To verify contracts on Etherscan, run:");
    console.log(`   npx hardhat verify --network ${networkName} ${factoryAddress} "${TREASURY_ADDRESS}"`);
  }

  console.log("\n✅ Deployment complete!");
  console.log("\n📋 Next Steps:");
  console.log("1. Update client/.env.local with the factory address");
  console.log(`2. Set NEXT_PUBLIC_VOTING_FACTORY_ADDRESS=${factoryAddress}`);
  console.log("3. Set NEXT_PUBLIC_CHAIN_ID=" + chainId);
  if (networkName === "sepolia") {
    console.log("4. Make sure you have Sepolia ETH in your wallet");
    console.log("5. Test the DApp on Sepolia testnet");
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });
